name: metadata

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'image tag.'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name/app
          tags: |
            type=sha,format=short,prefix=
            type=sha,format=long,prefix=
            type=raw,value=${{ inputs.image_tag }}
            type=raw,value=latest



      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var tags = `${{ steps.meta.outputs.tags }}`
              .replace(/%/g, '%25')
              .replace(/\n/g, '%0A')
              .replace(/\r/g, '%0D');
            await core.summary
              .addHeading('Image Tags')
              .addRaw(tags)
              .write()
