name: Environment Secrets

on:
  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com
    steps:
      - name: ok
        run: echo "development"

  staging:
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://google.com
    steps:
      - name: ok
        run: echo "staging"

  production:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://yahoo.com
    steps:
      - name: deploy
        run: echo "production"
