name: get-env-secret

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'target environment'
        required: true
        type: choice
        default: staging
        options:
        - staging
        - production

env:
  ENV_DATA_STAGING: staging-environment
  ENV_DATA_PRODUCTION: production-environment

jobs:
  setup-vars:
    name: Setup Vars
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      env-data: ${{ steps.env-data.outputs.ed }}
    steps:
    - name: Env Data
      id: env-data
      run: |
        if [ "${{ github.event.inputs.target }}" == "production" ]; then
          env_data="${{ env.ENV_DATA_PRODUCTION }}"
        else
          env_data="${{ env.ENV_DATA_STAGING }}"
        fi
        echo "::set-output name=ed::${env_data}"

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [setup-vars]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo ${{ needs.setup-variables.outputs.env-data }}
