name: Manual Artifact

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target.'
        required: true
        default: ''
      skip:
        description: 'Skip.'
        required: false
        default: 'false'
      commit_hash:
        description: 'Commit hash.'
        required: false
        default: ''

jobs:
  prepare:
    name: Setup Variables
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      sha: ${{ steps.commit-hash.outputs.sha }}
      today: ${{ steps.date.outputs.date }}
    steps:
      - name: Commit hash
        id: commit-hash
        run: |
          if [ "${{ github.event.inputs.commit_hash }}" == "" ]; then
            sha=${{ github.sha }}
          else
            sha=${{ github.event.inputs.commit_hash }}
          fi
          echo "::set-output name=sha::${sha}"

      - name: Current date
        id: date
        run: echo "::set-output name=today::$(TZ=Asia/Tokyo date +'%Y%m%d')"

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.prepare.outputs.sha }}
          
      - name: Check checkout
        run: |
          echo ${{ needs.prepare.outputs.sha }}
          echo $(git rev-parse HEAD)

  upload-artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [prepare, build]
    steps:
      - name: Create artifact files
        run: |
          mkdir artifacts
          touch artifacts/tmp.txt

      - name: Upload artifact; inputs.target
        uses: actions/upload-artifact@v2
        with:
          name: inputs.target.${{ github.event.inputs.target }}
          path: artifacts/tmp.txt
          retention-days: 30

      - name: Upload artifact; inputs.skip
        uses: actions/upload-artifact@v2
        with:
          name: inputs.skip.${{ github.event.inputs.skip }}
          path: artifacts/tmp.txt
          retention-days: 30

      - name: Upload artifact; inputs.commit_hash
        uses: actions/upload-artifact@v2
        with:
          name: inputs.commit_hash.${{ github.event.inputs.commit_hash }}
          path: artifacts/tmp.txt
          retention-days: 30

      - name: Upload artifact; github.ref
        uses: actions/upload-artifact@v2
        with:
          name: ref.${{ github.ref }}
          path: artifacts/tmp.txt
          retention-days: 30
