name: Manual Artifact

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target.'
        required: true
        default: ''
      skip:
        description: 'Skip.'
        required: false
        default: 'false'
      commit_hash:
        description: 'Commit hash.'
        required: false
        default: ''

jobs:
  prepare:
    name: Setup Variables
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      sha: ${{ steps.commit-hash.outputs.sha }}
      today: ${{ steps.date.outputs.date }}
    steps:
      - name: Target Commit Hash
        id: commit-hash
        run: |
          if [ "${{ github.event.inputs.commit_hash }}" == "" ]; then
            sha=${{ github.sha }}
          else
            sha=${{ github.event.inputs.commit_hash }}
          fi
          echo "::set-output name=sha::${sha}"

      - name: Current date
        id: date
        run: echo "::set-output name=today::$(TZ=Asia/Tokyo date +'%Y%m%d')"

  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.prepare.outputs.sha }}
          
      - name: Check checkout
        run: |
          echo ${{ needs.prepare.outputs.sha }}
          echo $(git rev-parse HEAD)

      - name: Output the input parameters
        run: |
          echo "target     : ${{ github.event.inputs.target }}" >> /artifacts/inputs.txt
          echo "skip       : ${{ github.event.inputs.skip }}" >> /artifacts/inputs.txt
          echo "commit_hash: ${{ github.event.inputs.commit_hash }}" >> /artifacts/inputs.txt
          echo "ref        : ${{ github.ref }}" >> /artifacts/inputs.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.target }} / ${{ github.event.inputs.skip }} / ${{ github.event.inputs.commit_hash }}
          path: /artifacts/inputs.txt
          retention-days: 30
