name: pull-request-merge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: get pr_number
        id: pr
        run: |
          echo "name=pull_request_number::$(git log --format=%B -n 1 ${{ github.event.after }} | grep -m 1 'Merge pull request #' | sed 's/[^0-9]*\([0-9]\{1,\}\).*$/\1/')" >> $GITHUB_OUTPUT
      - name: Show URL
        run: |
          echo "${{ steps.pr.outputs.pull_request_number }}"
      - name: summary
        run: echo "### [PR \#${{ steps.pr.outputs.pull_request_number }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.pr.outputs.pull_request_number }})" >> $GITHUB_STEP_SUMMARY
