name: Release

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'build mode'
        required: true
        type: choice
        default: test
        options:
        - build
        - release

jobs:
  prepare:
    name: Setup Variables
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      version: ${{ steps.exe-version.outputs.version }}
    steps:
      - name: Exe Version
        id: exe-version
        run: |
          if [ "${{ github.event.inputs.mode }}" == "release" ]; then
            version=$(TZ=Asia/Tokyo date +'%Y.%-m.%-d').${{ github.run_number }}
          else
            version="0.0.0.${{ github.run_number }}"
          fi
          echo "::set-output name=version::${version}"
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
        architecture: "x64"
        cache: "pip"

    - name: Install Libs
      run: mkdir dist && touch dist/main.txt

    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-world
        path: dist/main.txt

  release:
    if: github.event.inputs.mode == 'release'
    needs: [prepare, build]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: hello-world

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "main.txt"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.prepare.outputs.version }}
