name: defaults access

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: .github/workflows

defaults:
  run:
    working-directory: .github/workflows

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: echo defaults
        run: |
          pwd
          ls -alh
          echo ${WORKING_DIRECTORY}
