name: defaults access

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: .github/workflows

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: echo defaults
        run: echo ${{ defaults.run }}
